"use strict";

import gulp from "gulp";
import gulpLoadPlugins from "gulp-load-plugins";
import browserSync from "browser-sync";
import runSequence from "run-sequence";
import del from "del";

const plugins = gulpLoadPlugins();


/*******************************************************************************
                                  MAIN TASKS                                   *
*******************************************************************************/

// Generate CSS files from SCSS files and inyect css changes in browserSync
gulp.task("sass", () => {
  return gulp.src("src/scss/*.scss")
    .pipe(plugins.sourcemaps.init())
    .pipe(plugins.sass())
    .pipe(plugins.sourcemaps.write({includeContent: false}))
    .pipe(plugins.sourcemaps.init({loadMaps: true})) // Load sourcemaps generated by sass
    .pipe(plugins.autoprefixer({browsers: ["last 3 versions"]}))
    .on("error", plugins.util.log)
    .pipe(plugins.sourcemaps.write("."))
    .pipe(gulp.dest("src/css"))
    .pipe(browserSync.stream())
    .on("error", plugins.util.log);
});

// Lint JS files
gulp.task("lint", () => {
  return gulp.src(["src/**/*.js", "!src/config.js", "!src/node_modules/**/*.js", "!src/jspm_packages/**/*.js"])
    .pipe(plugins.cached("js")) //Process only changed files
    .pipe(plugins.eslint())
    .pipe(plugins.eslint.format())
    .pipe(plugins.eslint.failOnError());
});

// BrowserSync Server
gulp.task("serve", ["sass", "lint"], () => {
  browserSync.init([
    "src/js/**/*.js",
    "src/**/*.html"
  ], {
    notify: false,
    server: {
      baseDir: ["src"]
    },
    port: 3001,
    tunnel: false
  });

  gulp.watch("src/**/*.scss", ["sass"]);
  gulp.watch("src/**/*.js", ["lint"]);
});

// Default
gulp.task("default", ["serve"]);


/*******************************************************************************
*                              DISTRIBUTION TASKS                              *
*******************************************************************************/

// Minify images
gulp.task("images", () => {
  return gulp.src("src/images/**/*")
    .pipe(plugins.cache(plugins.imagemin({
      progressive: true,
      interlaced: true,
      // don"t remove IDs from SVGs, they are often used
      // as hooks for embedding and styling
      svgoPlugins: [{cleanupIDs: false}]
    })))
    .pipe(gulp.dest("dist/images"));
});

// Optmize CSS
gulp.task("css", () => {
  return gulp.src("src/css/*.css")
    .pipe(plugins.csso())
    .pipe(gulp.dest("dist/css"))
    .on("error", plugins.util.log);
});


// Minify HTML
gulp.task("html", () => {
  var opts = {
    conditionals: true
  };
  return gulp.src("src/**/*.html")
    .pipe(plugins.minifyHtml(opts))
    .pipe(gulp.dest("dist"));
});

// Copy files to "dist"
gulp.task("files", () => {
  return gulp.src(["src/*.*", "CNAME"], {dot: true}).pipe(gulp.dest("dist"));
});

// Delete dist Directory
gulp.task("clean", del.bind(null, ["dist"]));

// Copy JSPM files to dist
gulp.task("jspm", () => {
  return gulp.src("src/jspm_packages/**/*").pipe(gulp.dest("dist/jspm_packages"));
});

// Copy JS files to dist
gulp.task("js", ["lint"], () => {
  return gulp.src("src/**/*.js").pipe(gulp.dest("dist/"));
});

// Bundle with jspm
gulp.task("bundle", ["js", "jspm"], plugins.shell.task([
  "cd dist; jspm bundle app.js dist.js --inject "
]));

// Uglify the bundle
gulp.task("uglify", () => {
  return gulp.src("dist/dist.js")
    .pipe(plugins.sourcemaps.init({
      loadMaps: true
    }))
    .pipe(plugins.uglify())
    .pipe(plugins.sourcemaps.write("."))
    .pipe(gulp.dest("dist"))
    .on("error", plugins.util.log);
});

// Gzip distributable
gulp.task("gzip", () => {
  return gulp.src("dist/**/*").pipe(plugins.size({title: "build", gzip: true}));
});

// Main build task
gulp.task("build", () => {
  runSequence(
    "clean",
    "files",
    "sass",
    ["css", "images", "html", "bundle"],
    "uglify",
    "gzip"
  );
});
